cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
      instance-profile: true
    region:
      auto: true
      static: us-east-2
    stack:
      auto: false
    end-point: https://sqs.us-east-2.amazonaws.com/375170284425/testqueue
    email.bucketName: com.prapps.test.email-bucket
